### ISSUE TITLE
Getting RuntimeErrors when attempting to locate files in `templates/default` directory

### ISSUE THREAD

**Issue by jgarber623** [phlipper/chef-postgresql#144]
On a new Ubuntu 14.04 server, using [librarian-chef](https://github.com/applicationsonline/librarian-chef), and a pretty standard PostgreSQL configuration, I see the following error related to templates:

```
Recipe: postgresql::configuration
  * directory[/etc/postgresql/9.4/main/] action create (up to date)
  * template[/etc/postgresql/9.4/main/environment] action create
    
    ================================================================================
    Error executing action `create` on resource 'template[/etc/postgresql/9.4/main/environment]'
    ================================================================================
    
    RuntimeError
    ------------
    File templates/default/environment.erb does not exist for cookbook postgresql
    
    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks-2/chef-postgresql/recipes/configuration.rb
    
     16: template "/etc/postgresql/#{pg_version}/main/environment" do
     17:   source "environment.erb"
     18:   owner  "postgres"
     19:   group  "postgres"
     20:   mode   "0644"
     21:   notifies restart_action, "service[postgresql]"
     22: end
     23: 
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks-2/chef-postgresql/recipes/configuration.rb:16:in `from_file'
    
    template("/etc/postgresql/9.4/main/environment") do
      action "create"
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/etc/postgresql/9.4/main/environment"
      backup 5
      atomic_update true
      source "environment.erb"
      declared_type :template
      cookbook_name :postgresql
      recipe_name "configuration"
      mode "0644"
      owner "postgres"
      group "postgres"
    end
    

Running handlers:
[2015-02-24T11:17:26-05:00] ERROR: Running exception handlers
Running handlers complete
[2015-02-24T11:17:26-05:00] ERROR: Exception handlers complete
[2015-02-24T11:17:26-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 3 resources updated in 5.615789812 seconds
[2015-02-24T11:17:26-05:00] ERROR: template[/etc/postgresql/9.4/main/environment] (postgresql::configuration line 16) had an error: RuntimeError: File templates/default/environment.erb does not exist for cookbook postgresql
[2015-02-24T11:17:26-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

In testing, I found the same error occurs on any files in `templates/default`. For some reason, that directory can't be located.

I'm defining attributes in JSON and running the following recipes in order:

- recipe[postgresql::libpq]
- recipe[postgresql::server]
- recipe[postgresql::server_dev]
- recipe[postgresql::client]

Has anyone else run into this error? Any idea how to fix it?

Thanks!

**Comment by valtoni** [comment]
I have same trouble.

Starting Chef Client, version 12.0.3
Compiling Cookbooks...
[2015-03-03T02:28:02+00:00] WARN: Cloning resource attributes for file[/usr/sbin/policy-rc.d] from prior resource (CHEF-3694)
[2015-03-03T02:28:02+00:00] WARN: Previous file[/usr/sbin/policy-rc.d]: /var/chef/cookbooks/chef-postgresql/recipes/server.rb:9:in `from_file'
[2015-03-03T02:28:02+00:00] WARN: Current  file[/usr/sbin/policy-rc.d]: /var/chef/cookbooks/chef-postgresql/recipes/service.rb:6:in `from_file'
Converging 23 resources
Recipe: postgresql::default
  * apt_preference[pgdg] action add
    * directory[/etc/apt/preferences.d] action create (up to date)
    * file[/etc/apt/preferences.d/pgdg.pref] action create (up to date)
    * file[/etc/apt/preferences.d/pgdg] action delete (up to date)
     (up to date)
  * directory[/etc/apt/preferences.d] action nothing (skipped due to action :nothing)
  * file[/etc/apt/preferences.d/pgdg] action nothing (skipped due to action :nothing)
  * file[/etc/apt/preferences.d/pgdg.pref] action nothing (skipped due to action :nothing)
Recipe: postgresql::apt_repository
  * apt_repository[apt.postgresql.org] action add
    * remote_file[/opt/chef/ACCC4CF8.asc] action create (up to date)
    * execute[install-key ACCC4CF8.asc] action run (skipped due to not_if)
    * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
    * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
    * execute[apt-get update] action nothing (skipped due to action :nothing)
    * file[/etc/apt/sources.list.d/apt.postgresql.org.list] action create (up to date)
     (up to date)
  * apt_package[pgdg-keyring] action install (up to date)
Recipe: postgresql::default
  * apt_package[postgresql-common] action install (up to date)
Recipe: postgresql::server
  * file[/usr/sbin/policy-rc.d] action create (up to date)
  * apt_package[postgresql-9.4] action install (up to date)
Recipe: postgresql::data_directory
  * directory[/var/lib/postgresql/9.4/main] action create (skipped due to not_if)
  * bash[postgresql initdb] action run (skipped due to not_if)
Recipe: postgresql::configuration
  * directory[/etc/postgresql/9.4/main/] action create (up to date)
  * template[/etc/postgresql/9.4/main/environment] action create
    
    ================================================================================
    Error executing action `create` on resource 'template[/etc/postgresql/9.4/main/environment]'
    ================================================================================
    
    RuntimeError
    ------------
    File templates/default/environment.erb does not exist for cookbook postgresql
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cookbooks/chef-postgresql/recipes/configuration.rb
    
     16: template "/etc/postgresql/#{pg_version}/main/environment" do
     17:   source "environment.erb"
     18:   owner  "postgres"
     19:   group  "postgres"
     20:   mode   "0644"
     21:   notifies restart_action, "service[postgresql]"
     22: end
     23: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cookbooks/chef-postgresql/recipes/configuration.rb:16:in `from_file'
    
    template("/etc/postgresql/9.4/main/environment") do
      action "create"
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/etc/postgresql/9.4/main/environment"
      backup 5
      atomic_update true
      source "environment.erb"
      declared_type :template
      cookbook_name :postgresql
      recipe_name "configuration"
      owner "postgres"
      group "postgres"
      mode "0644"
    end
    

Running handlers:
[2015-03-03T02:28:03+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-03-03T02:28:03+00:00] ERROR: Exception handlers complete
[2015-03-03T02:28:03+00:00] FATAL: Stacktrace dumped to /opt/chef/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.519481046 seconds
[2015-03-03T02:28:03+00:00] ERROR: template[/etc/postgresql/9.4/main/environment] (postgresql::configuration line 16) had an error: RuntimeError: File templates/default/environment.erb does not exist for cookbook postgresql
[2015-03-03T02:28:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by jgarber623** [comment]
It appears that Chef 12 introduced a breaking change where a cookbook's name must match the path to which its installed. In this case, `postgresql` (the cookbook's name as defined in metadata) differs from the path in which it's installed (`chef-postgresql`).

See [this ticket](https://tickets.opscode.com/browse/CHEF-3490) for more details.

**Comment by jgarber623** [comment]
If you're using [Librarian-Chef](https://github.com/applicationsonline/librarian-chef), you can use the following in your Cheffile to get things working correctly:

`cookbook 'postgresql', git: 'https://github.com/phlipper/chef-postgresql'`
